title:              El Blog de Mateo
email:              mateo.romero.contreras@gmail.com
description:        Un blog de trabajo
author:             Mateo Romero
baseurl:            "/startbootstrap-clean-blog-jekyll"
url:                "https://startbootstrap.github.io"

# Social Profiles
twitter_username:
github_username:    mateoromerocontreras
facebook_username:
instagram_username:  mateo_rom_
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

theme: jekyll-theme-clean-blog